# Generated by Django 2.2 on 2019-04-07 19:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
                ('contactEmail', models.EmailField(max_length=254)),
                ('subjectAreaText', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200)),
                ('emailField', models.EmailField(max_length=254)),
                ('passwordField', models.CharField(max_length=18)),
                ('passwordConfirmField', models.CharField(max_length=18)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.IntegerField(default=1005, editable=False, primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=200)),
                ('bookerName', models.CharField(max_length=200)),
                ('bookerEmailField', models.EmailField(max_length=254)),
                ('phoneField', models.CharField(max_length=200)),
                ('eventStartTime', models.DateField(default=datetime.datetime.now)),
                ('eventEndTime', models.DateField(default=datetime.datetime.now)),
                ('numberOfPeople', models.IntegerField(default=0)),
                ('comment', models.TextField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
