# Generated by Django 2.2 on 2019-04-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalkitchenapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.IntegerField(default=372385, editable=False, primary_key=True, serialize=False),
        ),
    ]
