# Generated by Django 2.2 on 2019-04-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('globalkitchenapp', '0002_auto_20190409_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
